from __future__ import annotations

import csv
import html
import io
from pathlib import Path
from typing import Any

from adbgath import __version__

from .files import atomic_write_json, atomic_write_text

SEVERITY_ORDER = {"critical": 5, "high": 4, "medium": 3, "low": 2, "info": 1, "informational": 1}


def normalize_report(data: dict[str, Any]) -> dict[str, Any]:
    findings = list(data.get("findings", []))
    findings.sort(
        key=lambda item: (-SEVERITY_ORDER.get(str(item.get("severity", "info")).lower(), 0), item.get("title", ""))
    )
    return {"tool": "adbgath", "version": __version__, **data, "findings": findings}


def markdown_report(data: dict[str, Any]) -> str:
    report = normalize_report(data)
    lines = [
        f"# {report.get('title', 'adbgath Security Report')}",
        "",
        f"- Tool version: `{__version__}`",
        f"- Project: `{report.get('project_id', 'n/a')}`",
        f"- Device: `{report.get('device_serial', 'n/a')}`",
        "",
        "## Executive Summary",
        "",
        report.get("executive_summary", "Automated evidence and findings generated by adbgath."),
        "",
        "## Findings",
        "",
    ]
    if not report["findings"]:
        lines.append("No findings were recorded.")
    for index, finding in enumerate(report["findings"], 1):
        lines.extend(
            [
                f"### {index}. {finding.get('title', 'Untitled finding')}",
                "",
                f"- **Rule:** `{finding.get('rule_id', 'n/a')}`",
                f"- **Severity:** `{str(finding.get('severity', 'info')).upper()}`",
                f"- **Confidence:** `{finding.get('confidence', 'medium')}`",
                f"- **Status:** `{finding.get('status', 'open')}`",
                f"- **Component:** `{finding.get('component', 'n/a')}`",
                "",
                finding.get("description", ""),
                "",
                f"**Evidence:** {finding.get('evidence', 'Not recorded.')}",
                "",
                f"**Impact:** {finding.get('impact', 'Manual review required.')}",
                "",
                f"**Validation:** {finding.get('validation', 'Validate on an authorized test device.')}",
                "",
                f"**False-positive conditions:** {finding.get('false_positive', 'None documented.')}",
                "",
                f"**Remediation:** {finding.get('mitigation', 'Review the affected configuration.')}",
                "",
                f"**References:** {', '.join(finding.get('references', [])) or 'None'}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def html_report(data: dict[str, Any]) -> str:
    report = normalize_report(data)
    cards = []
    for finding in report["findings"]:
        sev = html.escape(str(finding.get("severity", "info")).lower())
        refs = "".join(f"<li>{html.escape(str(ref))}</li>" for ref in finding.get("references", []))
        cards.append(
            f"""
<section class="finding severity-{sev}">
  <header><span>{html.escape(sev.upper())}</span><h2>{html.escape(str(finding.get("title", "Untitled finding")))}</h2></header>
  <dl>
    <dt>Rule</dt><dd>{html.escape(str(finding.get("rule_id", "n/a")))}</dd>
    <dt>Confidence</dt><dd>{html.escape(str(finding.get("confidence", "medium")))}</dd>
    <dt>Status</dt><dd>{html.escape(str(finding.get("status", "open")))}</dd>
    <dt>Component</dt><dd>{html.escape(str(finding.get("component", "n/a")))}</dd>
  </dl>
  <h3>Description</h3><p>{html.escape(str(finding.get("description", "")))}</p>
  <h3>Evidence</h3><pre>{html.escape(str(finding.get("evidence", "Not recorded.")))}</pre>
  <h3>Impact</h3><p>{html.escape(str(finding.get("impact", "Manual review required.")))}</p>
  <h3>Validation</h3><p>{html.escape(str(finding.get("validation", "Validate on an authorized test device.")))}</p>
  <h3>False-positive conditions</h3><p>{html.escape(str(finding.get("false_positive", "None documented.")))}</p>
  <h3>Remediation</h3><p>{html.escape(str(finding.get("mitigation", "Review the affected configuration.")))}</p>
  <h3>References</h3><ul>{refs or "<li>None</li>"}</ul>
</section>"""
        )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(str(report.get("title", "adbgath report")))}</title>
<style>
:root{{font-family:Inter,system-ui,sans-serif;color:#e8edf6;background:#080b12}}body{{margin:0;padding:32px;max-width:1200px;margin:auto}}header.hero{{padding:32px;border:1px solid #26334b;border-radius:18px;background:#101624}}h1{{margin:0 0 8px}}.meta{{color:#9fb0cc}}.finding{{margin:24px 0;padding:24px;border-radius:16px;background:#101624;border-left:6px solid #62708a}}.finding header{{display:flex;gap:12px;align-items:center}}.finding header span{{font-weight:800}}.severity-critical{{border-color:#ff4060}}.severity-high{{border-color:#ff7452}}.severity-medium{{border-color:#f4c15d}}.severity-low{{border-color:#57b8ff}}dl{{display:grid;grid-template-columns:140px 1fr;gap:6px}}dt{{color:#9fb0cc}}pre{{white-space:pre-wrap;background:#070a10;padding:16px;border-radius:10px;overflow:auto}}a{{color:#66d9ef}}
</style></head><body>
<header class="hero"><h1>{html.escape(str(report.get("title", "adbgath Security Report")))}</h1><div class="meta">adbgath {__version__} · {len(report["findings"])} findings</div><p>{html.escape(str(report.get("executive_summary", "Automated evidence and findings generated by adbgath.")))}</p></header>
{"".join(cards) or "<p>No findings were recorded.</p>"}
</body></html>"""


def sarif_report(data: dict[str, Any]) -> dict[str, Any]:
    report = normalize_report(data)
    rules: dict[str, dict[str, Any]] = {}
    results = []
    level_map = {"critical": "error", "high": "error", "medium": "warning", "low": "note", "info": "note"}
    for finding in report["findings"]:
        rule_id = str(finding.get("rule_id", "ADBGATH-UNKNOWN"))
        rules.setdefault(
            rule_id,
            {
                "id": rule_id,
                "name": str(finding.get("title", rule_id)).replace(" ", "_"),
                "shortDescription": {"text": finding.get("title", rule_id)},
                "fullDescription": {"text": finding.get("description", "")},
                "help": {"text": finding.get("mitigation", "")},
                "properties": {"tags": finding.get("references", [])},
            },
        )
        result: dict[str, Any] = {
            "ruleId": rule_id,
            "level": level_map.get(str(finding.get("severity", "info")).lower(), "note"),
            "message": {"text": str(finding.get("evidence", finding.get("description", "")))},
            "properties": {"confidence": finding.get("confidence", "medium"), "status": finding.get("status", "open")},
        }
        location = finding.get("location")
        if location:
            result["locations"] = [{"physicalLocation": {"artifactLocation": {"uri": str(location)}}}]
        results.append(result)
    return {
        "version": "2.1.0",
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "runs": [
            {
                "tool": {"driver": {"name": "adbgath", "version": __version__, "rules": list(rules.values())}},
                "results": results,
            }
        ],
    }


def csv_report(data: dict[str, Any]) -> str:
    output = io.StringIO()
    fields = ["rule_id", "title", "severity", "confidence", "status", "component", "evidence", "mitigation"]
    writer = csv.DictWriter(output, fieldnames=fields, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(normalize_report(data)["findings"])
    return output.getvalue()


def pdf_report(data: dict[str, Any], output: Path) -> Path:
    """Write a self-contained PDF report without temporary HTML rendering."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    report = normalize_report(data)
    output.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ReportTitle", parent=styles["Title"], alignment=TA_CENTER, spaceAfter=12))
    styles.add(ParagraphStyle(name="FindingTitle", parent=styles["Heading2"], spaceBefore=10, spaceAfter=6))
    styles.add(
        ParagraphStyle(name="Evidence", parent=styles["Code"], fontSize=8, leading=10, leftIndent=6, rightIndent=6)
    )

    def text(value: Any) -> str:
        return html.escape(str(value if value not in {None, ""} else "n/a")).replace("\n", "<br/>")

    story = [
        Paragraph(text(report.get("title", "adbgath Security Report")), styles["ReportTitle"]),
        Paragraph(f"adbgath {html.escape(__version__)}", styles["Normal"]),
        Spacer(1, 4 * mm),
        Table(
            [
                ["Project", text(report.get("project_id", "n/a"))],
                ["Device", text(report.get("device_serial", "n/a"))],
                ["Findings", str(len(report["findings"]))],
            ],
            colWidths=[35 * mm, 135 * mm],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8EDF6")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#75839A")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]
            ),
        ),
        Spacer(1, 6 * mm),
        Paragraph("Executive Summary", styles["Heading1"]),
        Paragraph(
            text(report.get("executive_summary", "Automated evidence and findings generated by adbgath.")),
            styles["BodyText"],
        ),
        Spacer(1, 5 * mm),
        Paragraph("Findings", styles["Heading1"]),
    ]
    if not report["findings"]:
        story.append(Paragraph("No findings were recorded.", styles["BodyText"]))
    for index, finding in enumerate(report["findings"], 1):
        if index > 1:
            story.append(Spacer(1, 4 * mm))
        story.extend(
            [
                Paragraph(f"{index}. {text(finding.get('title', 'Untitled finding'))}", styles["FindingTitle"]),
                Table(
                    [
                        [
                            "Rule",
                            text(finding.get("rule_id", "n/a")),
                            "Severity",
                            text(str(finding.get("severity", "info")).upper()),
                        ],
                        [
                            "Confidence",
                            text(finding.get("confidence", "medium")),
                            "Status",
                            text(finding.get("status", "open")),
                        ],
                        ["Component", text(finding.get("component", "n/a")), "CWE", text(finding.get("cwe", "n/a"))],
                    ],
                    colWidths=[25 * mm, 57 * mm, 25 * mm, 63 * mm],
                    style=TableStyle(
                        [
                            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#A8B1C1")),
                            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EFF2F7")),
                            ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#EFF2F7")),
                            ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ]
                    ),
                ),
                Spacer(1, 2 * mm),
                Paragraph("Description", styles["Heading3"]),
                Paragraph(text(finding.get("description", "")), styles["BodyText"]),
                Paragraph("Evidence", styles["Heading3"]),
                Paragraph(text(finding.get("evidence", "Not recorded.")), styles["Evidence"]),
                Paragraph("Impact", styles["Heading3"]),
                Paragraph(text(finding.get("impact", "Manual review required.")), styles["BodyText"]),
                Paragraph("Validation", styles["Heading3"]),
                Paragraph(
                    text(finding.get("validation", "Validate on an authorized test device.")), styles["BodyText"]
                ),
                Paragraph("False-positive conditions", styles["Heading3"]),
                Paragraph(text(finding.get("false_positive", "None documented.")), styles["BodyText"]),
                Paragraph("Remediation", styles["Heading3"]),
                Paragraph(text(finding.get("mitigation", "Review the affected configuration.")), styles["BodyText"]),
                Paragraph("References", styles["Heading3"]),
                Paragraph(text(", ".join(finding.get("references", [])) or "None"), styles["BodyText"]),
            ]
        )
    story.extend(
        [
            PageBreak(),
            Paragraph("Appendix", styles["Heading1"]),
            Paragraph(
                "Generated by adbgath. Verify evidence hashes against the associated evidence manifest.",
                styles["BodyText"],
            ),
        ]
    )
    document = SimpleDocTemplate(
        str(output),
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=str(report.get("title", "adbgath Security Report")),
        author="adbgath",
    )
    document.build(story)
    return output


def write_report(data: dict[str, Any], output: Path, format_name: str) -> Path:
    format_name = format_name.lower()
    if format_name == "json":
        atomic_write_json(output, normalize_report(data))
    elif format_name in {"md", "markdown"}:
        atomic_write_text(output, markdown_report(data))
    elif format_name == "html":
        atomic_write_text(output, html_report(data))
    elif format_name == "csv":
        atomic_write_text(output, csv_report(data))
    elif format_name == "sarif":
        atomic_write_json(output, sarif_report(data))
    elif format_name == "pdf":
        pdf_report(data, output)
    else:
        raise ValueError(f"Unsupported report format: {format_name}")
    return output
